[package]
name = "icedmain"
version = "0.0.0"
edition = "2018"
publish = false

[workspace]

[[bin]]
name = "iced-main"
path = "main.rs"

[dependencies]
iced-macros = { path = "iced-macros" }
iced = { path = "iced" }
crc = { version = "2.0", git = "https://github.com/mrhooray/crc-rs.git" }
